apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  # this is the volume name that I claim
  # has to be the same as in the persisten volume yaml
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      # cant be more than what is the capacity of pv
      storage: 1Gi